# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item?useSSL=false&allowPublicKeyRetrieval=true
    username: root   # 数据库用户名
    password: 11111  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  # session 失效时间
  session:
    timeout: 86400
# 设置日志文件的文件名
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete # 逻辑删除字段名
      logic-delete-value: 1  # 逻辑删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  file:
    name: /logger/spring-book.log
server:
  port: 8080